# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/09_gan.core.ipynb (unless otherwise specified).

__all__ = ['WPDataset']

# Cell
# export
import torch

# Cell
# todo: erweitern/anpassen
class WPDataset(torch.utils.data.Dataset):

    def __init__(self, cont_data, cat_data=None, y=None):
        super(WPDataset, self).__init__()
        self.cont_data = cont_data
        self.cat_data = cat_data
        self.y = y

        if self.cat_data is None:
            self.cat_data = torch.empty((len(cont_data),1))

        if self.y is None:
            self.y = torch.empty((len(cont_data),1))

    def __len__(self):
        return len(self.cont_data)

    def __getitem__(self, idx):
        x_cont = self.cont_data[idx]
        x_cat = self.cat_data[idx]
        y = self.y[idx]

        return x_cat, x_cont, y