# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/09_gan.core.ipynb (unless otherwise specified).

__all__ = ['WPDataset', 'get_dataloaders']

# Cell
# export
from torch.utils.data import Dataset
import torch
import pickle

torch.cuda.is_available()

# Cell
class WPDataset(torch.utils.data.Dataset):

    def __init__(self, cont_data, cat_data=None):

        self.cont_data = cont_data
        self.cat_data = cat_data

        if self.cat_data is None:
            self.cat_data = torch.empty((len(cont_data),1))

    def __len__(self):
        return len(self.cont_data)

    def __getitem__(self, idx):
        y_cont = self.cont_data[idx]
        y_cat = self.cat_data[idx]

        return y_cat, y_cont

# Cell
def get_dataloaders(folder, idx='00'):
    data_dir = f'../../../../../data/preprocessed/{folder}/mtl_files/fold_{idx}_test.pkl'
    data = pickle.load(open(data_dir, 'rb'))
    dls = data.dataloaders()
    return dls