# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/09_gan.core.ipynb (unless otherwise specified).

__all__ = ['WPDataset']

# Cell
# export
from torch.utils.data import Dataset
import torch

# Cell
class WPDataset(Dataset):
    """TODO maik."""

    def __init__(self, data, noise_size=100):

        self.data = data
        self.noise_size = noise_size

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        y = self.data[idx]
        x = torch.rand(self.noise_size)

        return (x,y)