# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"contains_instance": "00a_utils.ipynb",
         "VILoss": "00b_losses.ipynb",
         "str_to_path": "01_tabular.core.ipynb",
         "read_hdf": "01_tabular.core.ipynb",
         "read_csv": "01_tabular.core.ipynb",
         "read_files": "01_tabular.core.ipynb",
         "RenewablesTabularProc": "01_tabular.core.ipynb",
         "CreateTimeStampIndex": "01_tabular.core.ipynb",
         "get_samples_per_day": "01_tabular.core.ipynb",
         "Interpolate": "01_tabular.core.ipynb",
         "FilterInconsistentSamplesPerDay": "01_tabular.core.ipynb",
         "AddSeasonalFeatures": "01_tabular.core.ipynb",
         "FilterByCol": "01_tabular.core.ipynb",
         "FilterYear": "01_tabular.core.ipynb",
         "FilterMonths": "01_tabular.core.ipynb",
         "FilterDays": "01_tabular.core.ipynb",
         "DropCols": "01_tabular.core.ipynb",
         "Normalize": "01_tabular.core.ipynb",
         "BinFeatures": "01_tabular.core.ipynb",
         "RenewableSplits": "01_tabular.core.ipynb",
         "ByWeeksSplitter": "01_tabular.core.ipynb",
         "TabularRenewables": "01_tabular.core.ipynb",
         "ReadTabBatchRenewables": "01_tabular.core.ipynb",
         "TabDataLoaderRenewables": "01_tabular.core.ipynb",
         "NormalizePerTask": "01_tabular.core.ipynb",
         "TabDataset": "01_tabular.core.ipynb",
         "TabDataLoader": "01_tabular.core.ipynb",
         "TabDataLoaders": "01_tabular.core.ipynb",
         "RenewableDataLoaders": "02_tabular.data.ipynb",
         "EmbeddingType": "03_tabular.model.ipynb",
         "get_emb_sz_list": "03_tabular.model.ipynb",
         "EmbeddingModule": "03_tabular.model.ipynb",
         "MultiLayerPerceptron": "03_tabular.model.ipynb",
         "get_structure": "03_tabular.model.ipynb",
         "RenewableLearner": "04_tabular.learner.ipynb",
         "renewable_learner": "04_tabular.learner.ipynb",
         "Timeseries": "05_timeseries_core.ipynb",
         "TimeseriesTransform": "05_timeseries_core.ipynb"}

modules = ["utils.py",
           "losses.py",
           "tabular/core.py",
           "tabular/data.py",
           "tabular/model.py",
           "tabular/learner.py",
           "timeseries/core.py"]

doc_url = "https://scribbler00.github.io/fastrenewables/"

git_url = "https://github.com/scribbler00/fastrenewables/tree/master/"

def custom_doc_links(name): return None
