# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00a_utils.ipynb (unless otherwise specified).

__all__ = ['contains_instance']

# Cell
def contains_instance(elements:list, instance):
    contains=False
    elements = list(elements)
    for element in elements:
        if isinstance(element, instance):
            contains=True
            break
    return contains