# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00a_utils.ipynb (unless otherwise specified).

__all__ = ['contains_instance', 'filter_preds']

# Cell
#export
from fastcore.test import *
import numpy as np

# Cell
def contains_instance(elements:list, instance):
    contains=False
    elements = list(elements)
    for element in elements:
        if isinstance(element, instance):
            contains=True
            break
    return contains

# Cell
def filter_preds(targets, preds, min_value=0, max_value=1.1, filter_nas=True):
    preds[preds < min_value] = min_value
    preds[preds > max_value] = max_value

    if filter_nas:
        mask_nans = ~np.isnan(preds)
        preds, targets = preds[mask_nans], targets[mask_nans]

    return targets, preds